name: Deployment Workflow

# Trigger this workflow on pushes to the specified branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

#      - name: Create .env file
#        uses: SpicyPizza/create-envfile@v1
#        with:
#          envkey_NODE_ENV: ${{ secrets.NODE_ENV }}
#          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
#          envkey_SHADOW_DATABASE_URL: ${{ secrets.SHADOW_DATABASE_URL }}
#          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
#          envkey_NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
#          envkey_AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
#          envkey_AZURE_AD_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
#          envkey_AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
#          envkey_SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
#          envkey_CONTACTS_MAIL_ADDRESS_FROM: ${{ env.CONTACTS_MAIL_ADDRESS_FROM }}
#          envkey_CONTACTS_MAIL_ADDRESS_TO: ${{ env.CONTACTS_MAIL_ADDRESS_TO }}
#          envkey_JOIN_US_MAIL_ADDRESS_FROM: ${{ env.JOIN_US_MAIL_ADDRESS_FROM }}
#          envkey_JOIN_US_MAIL_ADDRESS_TO: ${{ env.JOIN_US_MAIL_ADDRESS_TO }}
#          envkey_NEXT_PUBLIC_JOIN_US_MAX_FILE_SIZE: ${{ env.NEXT_PUBLIC_JOIN_US_MAX_FILE_SIZE }}

#      - name: Install dependencies
#        run: npm install

#      - name: Build Next.js app
#        run: npm run build

      - name: SSH Deploy
        # Use the 'appleboy/ssh-action' action for SSH deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # Your server's IP address
          username: ${{ secrets.USERNAME }} # Your server's username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Your server's SSH private key
          script: |
            cd /srv/ds-experts/git/ds-experts
            git pull
            # updating the .env file
            cat <<EOF > ${{ secrets.ENVFILE_PATH }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SHADOW_DATABASE_URL=${{ secrets.SHADOW_DATABASE_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            AZURE_AD_CLIENT_ID=${{ secrets.AZURE_AD_CLIENT_ID }}
            AZURE_AD_CLIENT_SECRET=${{ secrets.AZURE_AD_CLIENT_SECRET }}
            AZURE_AD_TENANT_ID=${{ secrets.AZURE_AD_TENANT_ID }}
            SENDGRID_API_KEY=${{ secrets.SENDGRID_API_KEY }}
            CONTACTS_MAIL_ADDRESS_FROM=${{ env.CONTACTS_MAIL_ADDRESS_FROM }}
            CONTACTS_MAIL_ADDRESS_TO=${{ env.CONTACTS_MAIL_ADDRESS_TO }}
            JOIN_US_MAIL_ADDRESS_FROM=${{ env.JOIN_US_MAIL_ADDRESS_FROM }}
            JOIN_US_MAIL_ADDRESS_TO=${{ env.JOIN_US_MAIL_ADDRESS_TO }}
            NEXT_PUBLIC_JOIN_US_MAX_FILE_SIZE=${{ env.NEXT_PUBLIC_JOIN_US_MAX_FILE_SIZE }}
            EOF
            # end of .env file
            npm ci
            npm run build
            npm run pm2:restart
